services:
  postgres:
    image: postgres:17-alpine
    container_name: iot-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iot-db
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - iot-network
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: iot-backend
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - iot-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/iot-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET-KEY: aiob+gN3NyYErzgX/3w0tw3ySC4wU+w6erPyoHuFS/4= # Example key
      JWT_EXPIRATION-MS: 86400000 # 24 hours

networks:
  iot-network:
    driver: bridge
