spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mqtt_data_hub_db
    username: postgres
    password: postgres

mqtt:
  broker:
    url: tcp://localhost:1883
  client:
    id: mqtt-data-hub-dev
  topic:
    sensor-data: +/+/+/sensor-data

logging:
  level:
    root: info
